<?php
get_header();
get_template_part("template/global","header");
get_template_part("template/home","slider");
get_template_part("template/home","about");
get_template_part("template/global","produtos");
get_template_part("template/global","clientes");
get_template_part("template/global","contato");
get_template_part("template/global","footer");
get_footer();